[package]
name = "rust_raytrace"
version = "0.1.0"
authors = ["danila.fomin <danila.fomin@corp.mail.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
threadpool = "1.8.1"
rayon = "1.5.1"
